  name: "Teste de Workflow 01"
  
  on: # Eventos de gatilho para o workflow
    push:
      branches:
        - main

  jobs: # Definição dos jobs do workflow (pode existir multiplos)
    job01:
      name: "Job de Teste 01"
      runs-on: ubuntu-latest # Especifica o ambiente de execução do job

      steps: # Passos do Job
        - name: "exibir teste"
          run: |
            echo "teste"
            ls -la
      
